class ClassWriter:
    def __init__(self, widget_structure):
        self.__widget_structure = widget_structure

    def to_file(self, path):
        code = []
        code.append("import pygame")
        code.append("")
        code.append("try:")
        code.append("\timport PygameXtras as pe")
        code.append("except:")
        code.append("\traise ModuleNotFoundError(\"It seems like you forgot to install the Pygame_Engine module\")")
        code.append("")
        code.append("try:")
        code.append("\tfrom pygame_xml_gui import SourceInserter, StyleInserter, SizeInserter, GUIMaker")
        code.append("except:")
        code.append("\traise ModuleNotFoundError(\"It seems like you forgot to install the pygame_xml_gui module\")")
        code.append("")
        code.append("class Methods:")
        code.append("")
        code.append("\tpass # in the future, all methods found in pyAction should go here")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")
        code.append("")



